# Generated by Django 4.1.4 on 2022-12-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_studyplan_user_delete_choice_delete_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudyPlanRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.user')),
            ],
            options={
                'db_table': 'user_study_plan',
            },
        ),
    ]
